# -*- coding: utf-8 -*-
"""sentence_builder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T70IHFbztf_F0-HggwvM1PN7jBmS_wPN
"""

!pip install -q gradio

import requests
import gradio as gr

def get_weather(location):
    url = f"https://forecast9.p.rapidapi.com/rapidapi/forecast/{location}/summary/"

    headers = {
        "X-RapidAPI-Key": "f142bb381cmshfca7ffb582f043ap18a3c2jsnefa24ba6a9a3",
        "X-RapidAPI-Host": "forecast9.p.rapidapi.com"
    }

    response = requests.request("GET", url, headers=headers)
    data = response.json()

    # Extract relevant weather details
    weather_data = data['forecast']['items'][0]

    temperature = f"Min: {weather_data['temperature']['min']}°C, Max: {weather_data['temperature']['max']}°C, Avg: {weather_data['temperature']['avg']}°C"
    weather = f"{weather_data['weather']['text']} ({weather_data['weather']['state']})"
    wind = f"{weather_data['wind']['text']} ({weather_data['wind']['direction']})"
    precipitation = f"{weather_data['prec']['sum']} mm"

    return temperature, weather, wind, precipitation

# Gradio interface
iface = gr.Interface(
    fn=get_weather,
    inputs=gr.inputs.Textbox(lines=1, placeholder="Enter location..."),
    outputs=[
        gr.outputs.Textbox(label="Temperature"),
        gr.outputs.Textbox(label="Weather"),
        gr.outputs.Textbox(label="Wind"),
        gr.outputs.Textbox(label="Precipitation"),
    ],
    title="Weather API",
    description="Enter a location to get the weather forecast.",
)

iface.launch()

